language: ruby
branches:
  only:
    - master

install:
  - gem install jekyll
  - gem install jekyll-scholar jekyll-sitemap
 
script:
  - JEKYLL_EVN=production jekyll build -d ~/website
  - cd ~/website
  - git init
  - git config user.name "Travis CI"
  - git config user.email "fberkenkamp@gmail.com"
  - git config --global push.default simple
  - git add .
  - git commit -m "Upload compiled website from travis"
  - git remote add production https://${GITHUB_TOKEN}@github.com/befelix/befelix.github.io.git
  - git push production master --force

