# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Felix Berkenkamp
email: befelix@inf.ethz.ch
description: > # this means to ignore newlines until "baseurl:"
  Felix Berkenkamp is a PhD student at the Learning and Adaptive Systems
  group at ETH Zurich. His research focuses on safe learning, with the
  goal of making robots learn without risking unsafe behavior during
  the learning process.
baseurl: "/befelix" # the subpath of your site, e.g. /blog
url: "http://people.inf.ethz.ch" # the base hostname & protocol for your site
github_username:  befelix

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
karmdown:
  input: GFM

scholar:
  style: assets/bibliography/bibstyle.csl
  locale: en

  sort_by: year,month
  order: descending

  group_by: none
  group_order: ascending

  source: assets/bibliography
  bibliography: bibliography.bib
  bibliography_template: bibtemplate

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex
  bibtex_skip_fields: [abstract,month_numeric,month,file,comment,pitch,video,code]

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
