# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Felix Berkenkamp
email: befelix@inf.ethz.ch
description: > # this means to ignore newlines until "baseurl:"
  Felix Berkenkamp is a PhD student at the Learning and Adaptive Systems
  group at ETH Zurich. His research focuses on safe learning, with the 
  goal of making robots learn without risking unsafe behavior during
  the learning process.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  befelix 

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
karmdown:
  input: GFM

