# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Felix Berkenkamp
email: fberkenkamp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Felix Berkenkamp is a research scientist at the Bosch Center for AI. He
  completed his PhD at ETH Zurich and his research focuses on safe learning, 
  with the goal of making real-world systems learn without risking unsafe 
  behavior during the learning process.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://berkenkamp.me" # the base hostname & protocol for your site
github_username:  befelix

permalink: /blog/:year-:month-:day-:title/

# Build settings
sass:
  sass_dir: _sass
  style: compressed

include: ['_pages']
kramdown:
  math_engine: mathjax

plugins_dir: ./_plugins
plugins:
  - jekyll-sitemap

# Exclude notebooks from sitemap. They are just exported html from ages ago and don't
# live up to modern web standards. They'll either go away or will need a proper solution
# at some point down the road.
defaults:
  -
    scope:
      path:            "assets/jupyter/**/*.html"
    values:
      sitemap:         false

scholar:
  style: _assets/bibliography/bibstyle.csl
  locale: en

  # While sorting by year,month is nice for bibliography, it is confusing in blog posts
  # Couldn't figure out how to have per-page sorting.
  sort_by: none #year,month
  order: descending

  group_by: none
  group_order: ascending

  source: _assets/bibliography
  bibliography: general
  bibliography_template: bibtemplate

  replace_strings: true
  join_strings:    true

  bibtex_filters:
  - superscript
  - latex
  bibtex_skip_fields: [abstract,month_numeric,month,file,comment,pitch,video,code,jupyter,slides,talk]

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
