version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-browsers-legacy
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: gem install jekyll jekyll-scholar jekyll-sitemap
      - run:
          name: Build website
          command: JEKYLL_ENV=production jekyll build -d ~/website
      - run:
          name: Upload
          working_directory: ~/website
          command: |
            git init
            git config credential.helper 'cache --timeout=120'
            git config user.name "CI"
            git config user.email "fberkenkamp@gmail.com"
            git add .
            git commit -m "Upload compiled website from CI"
            git remote add production https://${GITHUB_TOKEN}@github.com/befelix/befelix.github.io.git
            git push --quiet --force production master

workflows:
    version: 2
    build_and_deploy:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - master
